CREATE TABLE HUMIDITY_LOG (
  READING_TIME   TIMESTAMP PRIMARY KEY,
  READING_VALUE  NUMBER
);

CREATE TABLE LIGHT_LOG (
  READING_TIME   TIMESTAMP PRIMARY KEY,
  READING_VALUE  NUMBER
);

CREATE TABLE PUMP_COMMANDS (
  COMMAND_TIME   TIMESTAMP PRIMARY KEY,
  PUMP           CHAR(1),
  PERIOD         NUMBER
);

CREATE TABLE PING_FAILS (
  COMMAND_TIME   TIMESTAMP PRIMARY KEY,
);
